create table phone (id int8 generated by default as identity, number varchar(255) not null, prefix int4 not null, traveler_id int8, primary key (id));
create table traveler (id int8 generated by default as identity, document varchar(255), email varchar(255) not null, name varchar(255) not null, status varchar(255) not null, primary key (id));
alter table if exists phone add constraint FKi7i46m0pmxaaglikpfwue7rbe foreign key (traveler_id) references traveler;
