spring:
  application:
    name: bkn-traveler
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bkn-traveler
    username: postgres
    password: PGFamo2369

server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
